Adds option to recurse git submodules when finding source files
codecov/codecov-bash pull request #351
Opened 2020-09-21 19:25 UTC by rickpasetto

## Purpose
Some repos have source files in git submodules. The current script's methodology of finding source files in git is using `git ls-files`, which will not, by default, search submodules.  This adds a flag, `-E`, to the bash uploader which will pass `--recurse-submodules` to `git ls-files` when it gathers source files for upload.  This flag is optional; the default is to not recurse submodules.

## Notable Changes
Are there any changes that need to be called out as particularly tricky or significant?
_No_

## Tests and Risks?
Is this covered by existing tests? New ones? If no, why not?
_As far as I know, no tests check this, and there are no new ones that test this._

## Update the SHA hash files

Also make sure that you update all the hash files by running `for i in 1 256 512; do shasum -a "${i}" codecov > "SHA${i}SUM"; done`.
✅

2020-09-23 23:31 UTC, thomasrockhu commented
@drazisil-codecov my only thought here is do we want this to be the default behavior?

2020-09-24 00:52 UTC, rickpasetto commented
@thomasrockhu @drazisil-codecov I didn't make it the default because I wasn't sure if it would break existing use cases.
As for using `-X`: I think that's a good idea.  I will test it locally and update this PR.

2020-09-24 14:08 UTC, thomasrockhu submitted a review, later dismissed
Small nit, barring the SHA change LGTM

2020-09-24 14:08 UTC, thomasrockhu commented on codecov
> +                 -X recursesubs   For git projects, recurse submodules when searching for source files
```suggestion
                 -X recursesubs   Enable recurse submodules in git projects when searching for source files
```

2020-09-24 17:12 UTC, rickpasetto commented
@thomasrockhu @drazisil-codecov Okay, this is ready for re-review now.  Sorry for all the followups...

2020-09-24 17:39 UTC, thomasrockhu requested changes
SHA update, but LGTM, thank you for all the changes

2020-09-24 19:03 UTC, thomasrockhu approved these changes

2020-09-25 17:03 UTC, merged